# Generated by Django 3.1.4 on 2020-12-28 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
