# Generated by Django 3.1.4 on 2020-12-28 10:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20201228_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
